"""
CLIP-based semantic classifier for mask classification.

Uses OpenAI's CLIP model to classify segmentation masks by comparing
image embeddings with text embeddings of class descriptions.
"""

import torch
import numpy as np
from PIL import Image
from typing import Any


class CLIPClassifier:
    """
    Semantic classifier using CLIP to assign labels to masks generated by MobileSAM.
    
    Instead of relying on HSV color analysis, this uses CLIP's vision-language
    understanding to classify regions based on semantic similarity.
    """
    
    # Class prompts - multiple descriptions per class for better matching
    # More specific prompts lead to better discrimination
    CLASS_PROMPTS = {
        "water": [
            "a rectangular swimming pool with clear blue water from above",
            "bright blue swimming pool aerial view",
            "turquoise pool water surface",
            "chlorinated pool water from satellite"
        ],
        "vegetation": [
            "dense green tree canopy from above",
            "green forest trees aerial view",
            "lush green garden foliage satellite",
            "thick vegetation cover from sky"
        ],
        "plantation": [
            "organized rows of crops aerial view",
            "agricultural field with parallel rows",
            "vineyard or orchard from above",
            "brown cultivated farmland"
        ],
        "building": [
            "roof of residential house from above",
            "gray or brown building rooftop satellite",
            "concrete building structure aerial",
            "metal or tile roof from sky"
        ]
    }
    
    # Confidence thresholds
    MIN_CONFIDENCE = 0.22  # Minimum to be considered valid
    WATER_BONUS = 0.05     # Boost water confidence (pools are distinctive)
    
    def __init__(self, device: str = "cuda"):
        """
        Initialize CLIP classifier.
        
        Args:
            device: Device to run inference on ('cuda' or 'cpu')
        """
        self.device = device
        self.model = None
        self.processor = None
        self.text_embeddings = None
        self.class_indices = {}
        self._load_model()
    
    def _load_model(self):
        """Load CLIP model and precompute text embeddings."""
        from transformers import CLIPProcessor, CLIPModel
        
        print("Loading CLIP model...")
        self.model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
        self.processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
        self.model.to(self.device)
        self.model.eval()
        
        # Precompute text embeddings for efficiency
        self._precompute_text_embeddings()
        print(f"CLIP classifier loaded on {self.device}")
    
    def _precompute_text_embeddings(self):
        """Precompute and cache text embeddings for all class prompts."""
        all_prompts = []
        idx = 0
        
        for class_name, prompts in self.CLASS_PROMPTS.items():
            self.class_indices[class_name] = list(range(idx, idx + len(prompts)))
            all_prompts.extend(prompts)
            idx += len(prompts)
        
        # Tokenize and encode all prompts at once
        inputs = self.processor(
            text=all_prompts, 
            return_tensors="pt", 
            padding=True,
            truncation=True
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            self.text_embeddings = self.model.get_text_features(**inputs)
            # Normalize for cosine similarity
            self.text_embeddings = self.text_embeddings / self.text_embeddings.norm(
                dim=-1, keepdim=True
            )
    
    def classify_mask(
        self, 
        image: np.ndarray, 
        mask: np.ndarray,
        min_mask_pixels: int = 100
    ) -> tuple[str, float]:
        """
        Classify a single mask using CLIP.
        
        Args:
            image: Original RGB image (H, W, 3)
            mask: Binary mask (H, W) as boolean or uint8
            min_mask_pixels: Minimum pixels required for valid classification
            
        Returns:
            Tuple of (class_name, confidence_score)
        """
        # Ensure mask is boolean
        if mask.dtype != bool:
            mask = mask.astype(bool)
        
        # Check minimum mask size
        if mask.sum() < min_mask_pixels:
            return "other", 0.0
        
        # Extract bounding box of masked region
        rows = np.any(mask, axis=1)
        cols = np.any(mask, axis=0)
        
        if not rows.any() or not cols.any():
            return "other", 0.0
        
        rmin, rmax = np.where(rows)[0][[0, -1]]
        cmin, cmax = np.where(cols)[0][[0, -1]]
        
        # Crop to bounding box
        cropped_image = image[rmin:rmax+1, cmin:cmax+1].copy()
        cropped_mask = mask[rmin:rmax+1, cmin:cmax+1]
        
        # Apply mask - set non-masked pixels to neutral gray
        # Gray is better than white for aerial imagery
        cropped_image[~cropped_mask] = [128, 128, 128]
        
        # Convert to PIL Image
        pil_image = Image.fromarray(cropped_image)
        
        # Get CLIP image embedding
        inputs = self.processor(images=pil_image, return_tensors="pt")
        inputs = {k: v.to(self.device) for k, v in inputs.items()}
        
        with torch.no_grad():
            image_embedding = self.model.get_image_features(**inputs)
            image_embedding = image_embedding / image_embedding.norm(dim=-1, keepdim=True)
        
        # Compute cosine similarity with all text embeddings
        similarities = (image_embedding @ self.text_embeddings.T).squeeze(0)
        
        # Aggregate scores by class (take max similarity among prompts)
        class_scores = {}
        for class_name, indices in self.class_indices.items():
            score = similarities[indices].max().item()
            # Apply water bonus - pools are very distinctive
            if class_name == "water":
                score += self.WATER_BONUS
            class_scores[class_name] = score
        
        # Get best matching class
        best_class = max(class_scores, key=class_scores.get)
        confidence = class_scores[best_class]
        
        # Log classification for debugging
        # print(f"  Mask {mask.sum()} px -> {best_class} ({confidence:.3f})")
        
        # Threshold - if confidence is too low, mark as "other"
        if confidence < self.MIN_CONFIDENCE:
            return "other", confidence
        
        return best_class, confidence
    
    def classify_masks_batch(
        self, 
        image: np.ndarray, 
        masks: list[np.ndarray]
    ) -> list[tuple[str, float]]:
        """
        Classify multiple masks efficiently.
        
        Args:
            image: Original RGB image (H, W, 3)
            masks: List of binary masks
            
        Returns:
            List of (class_name, confidence) tuples
        """
        results = []
        for mask in masks:
            result = self.classify_mask(image, mask)
            results.append(result)
        return results


# Singleton instance for efficiency
_classifier_instance: CLIPClassifier | None = None


def get_clip_classifier(device: str = "cuda") -> CLIPClassifier:
    """Get or create the global CLIP classifier instance."""
    global _classifier_instance
    if _classifier_instance is None:
        _classifier_instance = CLIPClassifier(device=device)
    return _classifier_instance
